[package]
name = "cuticula"
description = "Data Preprocessing library for Machine Learning"
authors = ["Michael Hirn <mj@autumnai.com>"]
version = "0.1.5"
repository = "https://github.com/autumnai/cuticula"
homepage = "https://github.com/autumnai/cuticula"
documentation = "http://autumnai.github.io/cuticula"
readme = "README.md"
keywords = ["preprocessing", "data-preprocessing", "transformation", "encoding",
"machine-learning"]
license = "MIT"

[dependencies]
phloem = "0.2.4"
image = "0.4.0"
murmurhash3 = "0.0.5"
modifier = "0.1"
clippy = {version = "0.0.33", optional = true}

[features]
default = []
dev = ["clippy"] 
